# Generated by Django 3.2 on 2021-05-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('author_eng', models.CharField(max_length=100, verbose_name='著者eng')),
                ('word_oder', models.CharField(choices=[('Aa', 'あ行'), ('Ka', 'か行'), ('Sa', 'さ行'), ('Ta', 'た行'), ('Na', 'な行'), ('Ha', 'は行'), ('Ma', 'ま行'), ('Ya', 'や行'), ('Ra', 'ら行'), ('Wa', 'わ行')], max_length=10, verbose_name='五十音')),
                ('age', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='性別')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Action', 'アクション'), ('Youth', '青春'), ('Love', '恋愛'), ('History', '時代'), ('Mystery', 'ミステリー'), ('Horror', 'ホラー')], max_length=20, verbose_name='カテゴリー')),
                ('category_eng', models.CharField(choices=[('Action_eng', 'Action'), ('Youth_eng', 'Youth'), ('Love_eng', 'Love'), ('History_eng', 'History'), ('Mystery_eng', 'Mystery'), ('Horror_eng', 'Horror')], max_length=20, verbose_name='カテゴリーeng')),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('pink', 'pink'), ('green', 'green'), ('purple', 'purple'), ('dark', 'dark')], max_length=20, verbose_name='色')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('incorporated', models.DateField(verbose_name='設立日')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100, verbose_name='シリーズ')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='タイトル')),
                ('pages', models.SmallIntegerField(null=True, verbose_name='ページ数')),
                ('issue', models.DateField(null=True, verbose_name='発行日')),
                ('youth_choices', models.CharField(choices=[('Y', 'Youth'), ('O', 'Old')], max_length=10, verbose_name='青春/白秋')),
                ('fin', models.SmallIntegerField(null=True, verbose_name='完読')),
                ('Author_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者情報')),
                ('category_info', models.ManyToManyField(blank=True, related_name='category_info', to='book.Category', verbose_name='カテゴリー情報')),
                ('publisher_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版社情報')),
                ('series_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='シリーズ情報')),
            ],
        ),
    ]
