# Generated by Django 3.2 on 2021-06-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('author_eng', models.CharField(max_length=100, verbose_name='著者eng')),
                ('word_oder', models.CharField(choices=[('Aa', 'あ行'), ('Ka', 'か行'), ('Sa', 'さ行'), ('Ta', 'た行'), ('Na', 'な行'), ('Ha', 'は行'), ('Ma', 'ま行'), ('Ya', 'や行'), ('Ra', 'ら行'), ('Wa', 'わ行')], max_length=10, verbose_name='五十音')),
                ('age', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(choices=[('Mon', '男性'), ('Womon', '女性')], max_length=10, verbose_name='性別')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('contents_lite', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('action', 'アクション'), ('adventure', 'アドベンチャー'), ('youth', '青春'), ('love', '恋愛'), ('sf', 'SF'), ('history', '時代'), ('mystery', 'ミステリー'), ('comedy', 'コメディー'), ('horror', 'ホラー')], max_length=20, verbose_name='カテゴリー')),
                ('category_eng', models.CharField(blank=True, choices=[('action', 'アクション'), ('adventure', 'アドベンチャー'), ('youth', '青春'), ('love', '恋愛'), ('sf', 'SF'), ('history', '時代'), ('mystery', 'ミステリー'), ('comedy', 'コメディー'), ('horror', 'ホラー')], max_length=20, null=True, verbose_name='カテゴリーeng')),
                ('color', models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('blue', 'blue'), ('pink', 'pink'), ('info', 'info'), ('green', 'green'), ('purple', 'purple'), ('warning', 'warning'), ('dark', 'dark')], max_length=20, verbose_name='色')),
                ('contents', models.TextField(blank=True, verbose_name='コンテンツ')),
                ('contents_keyword', models.TextField(blank=True, verbose_name='キーワード')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('publisher_eng', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版社_eng')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('incorporated', models.DateField(verbose_name='設立日')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.TextField(verbose_name='目次')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100, verbose_name='シリーズ')),
                ('contents', models.TextField(verbose_name='コンテンツ')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='タイトル')),
                ('pages', models.SmallIntegerField(null=True, verbose_name='ページ数')),
                ('issue', models.DateField(null=True, verbose_name='発行日')),
                ('post_day', models.DateField(null=True, verbose_name='投稿日')),
                ('youth_choices', models.CharField(choices=[('Y', 'Youth'), ('O', 'Old')], max_length=10, verbose_name='青春/白秋')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
                ('fin', models.SmallIntegerField(null=True, verbose_name='完読')),
                ('amazon_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='アマゾンURL')),
                ('Author_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者情報')),
                ('category_info', models.ManyToManyField(blank=True, related_name='category_info', to='book.Category', verbose_name='カテゴリー情報')),
                ('publisher_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版社情報')),
                ('series_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='シリーズ情報')),
            ],
        ),
    ]
