# Generated by Django 3.2 on 2021-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='post_day',
            field=models.DateField(null=True, verbose_name='投稿日'),
        ),
    ]
