# Generated by Django 3.2 on 2021-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_post_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='アマゾンURL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('Mon', '男性'), ('Womon', '女性')], max_length=10, verbose_name='性別'),
        ),
    ]
