# Generated by Django 3.2 on 2021-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210510_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='post_day',
            field=models.DateField(null=True, verbose_name='投稿日'),
        ),
        migrations.AddField(
            model_name='category',
            name='post_day',
            field=models.DateField(null=True, verbose_name='投稿日'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='post_day',
            field=models.DateField(null=True, verbose_name='投稿日'),
        ),
        migrations.AddField(
            model_name='series',
            name='post_day',
            field=models.DateField(null=True, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amazon_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='アマゾンURL'),
        ),
    ]
