# Generated by Django 3.2 on 2021-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210513_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contents',
            field=models.TextField(blank=True, verbose_name='コンテンツ'),
        ),
    ]
