# Generated by Django 3.2 on 2021-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_category_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contents_lite',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ'),
        ),
    ]
