# Generated by Django 3.2 on 2021-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_contents_lite'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出版社_eng'),
        ),
    ]
