# Generated by Django 3.2 on 2021-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_eng',
            field=models.CharField(choices=[('Action_eng', 'Action'), ('Youth_eng', 'Youth'), ('Love_eng', 'Love'), ('History_eng', 'History'), ('Mystery_eng', 'Mystery'), ('Horror_eng', 'Horror')], max_length=20, null=True, verbose_name='カテゴリーeng'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('blue', 'blue'), ('pink', 'pink'), ('info', 'info'), ('green', 'green'), ('purple', 'purple'), ('warning', 'warning'), ('dark', 'dark')], max_length=20, verbose_name='色'),
        ),
    ]
