# Generated by Django 3.2 on 2021-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210528_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_eng',
            field=models.CharField(blank=True, choices=[('Action_eng', 'Action'), ('Youth_eng', 'Youth'), ('Love_eng', 'Love'), ('History_eng', 'History'), ('Mystery_eng', 'Mystery'), ('Horror_eng', 'Horror')], max_length=20, null=True, verbose_name='カテゴリーeng'),
        ),
    ]
