# Generated by Django 3.2 on 2021-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ'),
        ),
    ]
