# Generated by Django 3.2 on 2021-06-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_eng',
            field=models.CharField(blank=True, choices=[('action', 'アクション'), ('adventure', 'アドベンチャー'), ('youth', '青春'), ('love', '恋愛'), ('sf', 'SF'), ('history', '時代'), ('mystery', 'ミステリー'), ('comedy', 'コメディー'), ('horror', 'ホラー')], max_length=20, null=True, verbose_name='カテゴリーeng'),
        ),
    ]
