# Generated by Django 3.2 on 2021-08-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_category_category_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(default=None, max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '未選択'), ('Mon', '男性'), ('Womon', '女性')], max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='著者情報'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fin',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='完読'),
        ),
        migrations.AlterField(
            model_name='book',
            name='issue',
            field=models.DateField(blank=True, null=True, verbose_name='発行日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='post_day',
            field=models.DateField(blank=True, null=True, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版社情報'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('action', 'アクション'), ('adventure', 'アドベンチャー'), ('youth', '青春'), ('love', '恋愛'), ('sf', 'SF'), ('history', '時代'), ('mystery', 'ミステリー'), ('comedy', 'コメディー'), ('horror', 'ホラー')], default=None, max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.CreateModel(
            name='Publisher_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=20, verbose_name='ラベル')),
                ('label_eng', models.CharField(default=None, max_length=20, verbose_name='ラベルeng')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher', verbose_name='出版者')),
            ],
        ),
    ]
