# Generated by Django 3.2 on 2021-08-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20210821_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_label_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher_label', verbose_name='レーベル'),
        ),
    ]
