# Generated by Django 3.1.6 on 2021-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=10)),
                ('youtube_video_title', models.CharField(max_length=100)),
                ('youtube_video_day', models.TimeField()),
                ('youtube_video_episode', models.SmallIntegerField()),
                ('manage_twitter_already', models.BooleanField()),
            ],
        ),
    ]
