# Generated by Django 3.1.6 on 2021-04-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='category_id')),
                ('category_jp', models.CharField(max_length=50, verbose_name='カテゴリーjp')),
                ('category_eng', models.CharField(max_length=50, verbose_name='カテゴリーeng')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='member_id')),
                ('member_jp', models.CharField(max_length=20, verbose_name='メンバーjp')),
                ('member_eng', models.CharField(max_length=20, verbose_name='メンバーeng')),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=10, null=True)),
                ('youtube_video_title', models.CharField(max_length=100, null=True)),
                ('youtube_video_day', models.DateTimeField(null=True)),
                ('youtube_video_episode', models.SmallIntegerField(null=True)),
                ('contents', models.CharField(max_length=500, null=True)),
                ('manage_twitter_already', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('members', models.ManyToManyField(related_name='members', to='app.Member')),
            ],
        ),
    ]
