# Generated by Django 3.1.6 on 2021-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_eng',
            field=models.CharField(max_length=50, null=True, verbose_name='カテゴリーeng'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_jp',
            field=models.CharField(max_length=50, null=True, verbose_name='カテゴリーjp'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='manage_twitter_already',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='member_id'),
        ),
    ]
