# Generated by Django 3.1.6 on 2021-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_day',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_episode',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
