# Generated by Django 3.1.6 on 2021-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210319_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='contents',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
