# Generated by Django 3.1.7 on 2021-04-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210410_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='contents',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_episode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='youtube_video_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
