# Generated by Django 3.1.7 on 2021-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210417_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='app.Member'),
        ),
    ]
