# Generated by Django 3.1.7 on 2021-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210417_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents_demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_demo', models.TextField(blank=True, null=True, verbose_name='コンテンツ')),
            ],
        ),
    ]
