# Generated by Django 3.1.7 on 2021-04-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contents_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents_demo',
            name='category_key',
            field=models.ForeignKey(blank=True, db_column='category_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
