# Generated by Django 3.1.7 on 2021-04-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210422_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents_demo',
            name='category_key',
            field=models.OneToOneField(blank=True, db_column='category_eng', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
