# Generated by Django 3.1.7 on 2021-04-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210422_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='contents',
            field=models.CharField(max_length=5000, null=True, verbose_name='コンテンツ'),
        ),
    ]
